package constants;

public enum RequestParameter {
    ALL_PARAMETERS,
    FIRST_PARAMETER_ONLY,
    SECOND_PARAMETER_ONLY,
    THIRD_PARAMETER_ONLY,
    FOURTH_PARAMETER_ONLY,
    FIFTH_PARAMETER_ONLY,
    SIXTH_PARAMETER_ONLY,
    NO_PARAMETERS,
    NO_API_KEY
}
